# Android CI/CD Pipeline
name: Android CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

# Environment variables
env:
  JAVA_VERSION: '17'
  ANDROID_SDK_TOOLS: '10406996'
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError'

# Permissions for security
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  # Job for code quality checks
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS }}

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results*.html
          retention-days: 7

  # Job for unit tests
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/
          retention-days: 7

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: app/build/test-results/testDebugUnitTest/TEST-*.xml
          reporter: java-junit
          fail-on-error: false

  # Job for UI tests
  ui-test:
    name: UI Tests
    runs-on: macos-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS }}

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install emulator dependencies
        run: |
          sdkmanager "system-images;android-30;google_apis;x86_64"
          sdkmanager --install "cmdline-tools;latest"
          sdkmanager --install "emulator"

      - name: Wait for emulator to be ready
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          disk-size: 4096M
          sdcard-size: 512M
          emulator-options: -no-snapshot -noaudio -no-boot-anim -accel on -gpu swiftshader_indirect
          script: |
            echo "Starting emulator boot checks..."
            for i in {1..30}; do
              adb devices | grep emulator && adb shell getprop sys.boot_completed | grep 1 && break
              echo "Waiting for emulator to boot... Attempt $i/30"
              sleep 10
            done
            adb devices
            if ! adb shell getprop sys.boot_completed | grep 1; then
              echo "Emulator failed to boot"
              adb logcat -d > emulator_logcat.txt
              exit 1
            fi
            ./gradlew connectedDebugAndroidTest --stacktrace

      - name: Upload Emulator Logcat
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: emulator-logcat
          path: emulator_logcat.txt
          retention-days: 7

      - name: Upload UI Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: app/build/reports/androidTests/connected/
          retention-days: 7

  # Job for building APKs
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS }}

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses || true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

      - name: Decode Keystore
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > keystore.jks
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      - name: Build Release APK
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          KEYSTORE_PATH: keystore.jks

      - name: Upload Release APK
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30
          if-no-files-found: error

  # Job for deploying to Play Store
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Release APK
        uses: actions/download-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CREDENTIALS }}
          packageName: com.example.app
          releaseFiles: app/build/outputs/apk/release/*.apk
          track: production
          status: completed
