# Android CI/CD Pipeline
name: Android CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

# Environment variables
env:
  JAVA_VERSION: '17'
  ANDROID_SDK_TOOLS: '10406996'
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError'

# Permissions for security
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  instrumentation-test:
    name: Instrumentation Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: '30'
          target: 'default'
          arch: 'x86_64'
          emulator-options: '-no-snapshot -no-boot-anim'
          script: |
            adb wait-for-device
            sleep 60
      - name: Restart ADB Server
        run: |
          adb kill-server
          adb start-server   

      - name: Capture Emulator Logs
        run: adb logcat > emulator.log     

      - name: Upload Instrumentation Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-report
          path: app/build/reports/androidTests/connected/
          retention-days: 7




