# Android CI/CD Pipeline
name: Android CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

# Environment variables
env:
  JAVA_VERSION: '17'
  ANDROID_SDK_TOOLS: '10406996'
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError'

# Permissions for security
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
 instrumentation-tests:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install Emulator and System Image
        run: |
          sdkmanager "platform-tools" "emulator" "platforms;android-33" "system-images;android-33;google_apis;x86_64"
          echo "y" | avdmanager create avd -n test_emulator -k "system-images;android-33;google_apis;x86_64" --device "pixel"

      - name: Start Emulator
        run: |
          nohup emulator -avd test_emulator -no-snapshot -no-window -no-audio -gpu swiftshader_indirect > /dev/null 2>&1 &
          adb wait-for-device
          adb shell input keyevent 82
          sleep 30

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload Instrumentation Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-results
          path: |
            **/build/reports/androidTests/connected/
            **/build/outputs/androidTest-results/




