# .github/workflows/android-ci-cd.yml
name: Android CI/CD

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

# Define environment variables
env:
  JAVA_VERSION: '17'  # Specify Java version
  ANDROID_SDK_TOOLS: '10406996'  # Latest Android SDK tools version as of 2025

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      # Step 3: Install Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS }}

      # Step 4: Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true

      # Step 5: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 6: Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 7: Run lint checks
      - name: Run Lint
        run: ./gradlew lintDebug
        
      # Upload HTML Lint Test Report as artifact  
      - name: Upload HTML Lint Test Report
        uses: actions/upload-artifact@v4
        with:
          name: index.html
          path: app/build/reports/lints-results-debug.html

      # Step 8: Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 9: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 10: Upload Debug APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
